@tool
class_name ActorShadow extends Decal

## A blob shadow: a black disc projected straight down onto whatever ground is under
## the actor, shrinking and fading as the actor rises away from it.
##
## [b]Why a decal and not a flat quad.[/b] The disc has to sit on ground this game does
## not promise is flat - tile edges, steps, the lip of a platform. A quad is a plane, so
## it either clips into a step or floats off it; a decal projects onto whatever geometry
## is inside its box and wraps all of that for free. The cost is a decal pass per actor,
## which at these actor counts is not a consideration.
##
## [b]Why it is its own node rather than something [SpriteView3D] spawns.[/b] The shadow
## is per-actor art with a radius and an opacity worth tuning in the inspector next to
## the sprite it belongs to, and making it a node means an actor that should not cast one
## simply does not have one - no "enabled" flag threaded through the view.
##
## [b]Where it goes in the scene.[/b] A direct child of the body, a sibling of [Actor]
## and the sprite - never under [ActorView], for the reason that class documents at
## length: a [Node3D] whose parent chain passes through a plain [Node] becomes its own
## transform root and renders at the world origin.

## What the shadow follows horizontally. Left empty it follows its parent, which is
## right for a free-moving actor and wrong for a grid-stepping one.
##
## [b]Why this is needed.[/b] Under [GridMotion] the body is authoritative and teleports
## a whole cell the instant a step commits; the sprite is a lie that tweens to catch up.
## A shadow tracking the body therefore snaps to the claimed square and waits there while
## the actor walks into it. Pointing this at the sprite makes the shadow follow the thing
## the eye is actually looking at. [CameraRig] has the same problem and solves it the
## same way - see [method CameraRig.focus_of].
##
## Only X and Z are taken from the target. Height comes from the parent regardless,
## because the sprite sits on a pedestal - a local Y offset that raises the art off the
## floor - and a shadow that read it would think the actor was permanently in the air and
## draw itself shrunk and faded while standing still. The parent body is the node that
## genuinely has a height, so a jump still reads correctly with no offset to configure.
@export var target_path: NodePath = NodePath() : set = _set_target_path

## Disc diameter on the ground, in world units, with the actor standing on it.
@export var radius: float = 0.35 : set = _set_radius

## Opacity with the actor standing on the ground. Fades to zero at [member max_height].
@export_range(0.0, 1.0, 0.01) var opacity: float = 0.55

## Height above the ground at which the shadow has shrunk to [member min_scale] and
## faded out entirely. Roughly the peak of a jump.
@export var max_height: float = 2.5

## How small the disc gets at [member max_height], as a fraction of [member radius].
## Not zero: the shadow should read as small and far, not as absent, right up until the
## opacity takes it.
@export_range(0.05, 1.0, 0.01) var min_scale: float = 0.4

## How far down to look for ground. Past this the actor is over a pit and the shadow
## hides rather than sticking to the last thing it saw.
@export var ray_length: float = 20.0

## What counts as ground. Everything by default, which is what makes this work against
## the floor collision the demos already have; narrow it if props start catching
## shadows they should not.
@export_flags_3d_physics var ground_mask: int = 0xFFFFFFFF

## Texels per world unit, matching the rest of the presentation. The disc texture is
## generated at this density so its edge is the same size as every other pixel in the
## frame rather than a smooth curve sitting on top of a pixel-art scene.
@export var texels_per_unit: int = 16 : set = _set_texels

## How deep the projection box is. Only has to be thick enough to contain the ground
## surface it is centred on; deeper would start catching the ceiling of the floor below.
@export var thickness: float = 0.4

var _exclude: Array[RID] = []
var _generated: ImageTexture = null
var _target: Node3D = null
var _ground_y: float = 0.0
var _grounded: bool = false


func _ready() -> void:
	# The disc is generated rather than authored because it is one circle, and an art
	# file would have to be regenerated by hand every time radius or the texel density
	# changed. An explicitly assigned texture still wins.
	if texture_albedo == null:
		_rebuild_texture()
	modulate = Color(0, 0, 0, opacity)
	# Mixing the decal's own albedo in rather than blending over it is what makes it a
	# shadow instead of a black sticker: the ground's colour still shows through.
	albedo_mix = 1.0
	_apply_size(1.0)

	_resolve_target()

	# Detached from the parent's transform, and this is the difference between working
	# and not.
	#
	# The shadow belongs on the ground in world space, and it is parented to the body
	# only so it lives with the actor in the scene. Left as an ordinary child it inherits
	# the body's motion, which is fatal under [GridMotion]: the body teleports a whole
	# cell at commit and drags the shadow with it, so the frame the step commits in
	# renders the shadow a cell ahead of the actor before the next physics tick puts it
	# back. One frame, one cell, and perfectly visible.
	top_level = true

	# Run after everything that moves the actor or writes the sprite - the input driver
	# commits steps in its own _process, and the rig writes sprite transforms in its.
	# Sampling before either would be a frame behind whatever the eye is about to see.
	process_priority = 100

	if Engine.is_editor_hint():
		return

	# The body's own collider sits directly above this node, and the ray starts a little
	# way up inside it. Ray queries ignore hits from inside a shape by default, but only
	# for the shape they started in - excluding the body outright is what stops a capsule
	# whose bottom is below the node origin from catching its own shadow.
	var body := get_parent() as CollisionObject3D
	if body != null:
		_exclude = [body.get_rid()]


## Finds the ground. Only the ground - where the disc actually goes is [method _process].
##
## The ray lives here because [PhysicsDirectSpaceState3D] is meant to be queried from the
## physics step; casting one while the server is flushing queries errors rather than
## returning a wrong answer. The height it finds is good for the whole frame, so the
## split costs nothing.
func _physics_process(_delta: float) -> void:
	if Engine.is_editor_hint():
		return
	var world := get_world_3d()
	if world == null:
		return
	var space := world.direct_space_state
	if space == null:
		# No physics world - a headless test building actors in code. Nothing to stand
		# on, so there is nothing to draw.
		_grounded = false
		visible = false
		return

	# Started slightly above the feet so an actor resting exactly on the floor is not
	# starting its ray on the surface it is looking for.
	var from := _origin() + Vector3.UP * 0.05
	var query := PhysicsRayQueryParameters3D.create(
			from, from + Vector3.DOWN * ray_length, ground_mask, _exclude)
	var hit := space.intersect_ray(query)
	_grounded = not hit.is_empty()
	if _grounded:
		_ground_y = (hit["position"] as Vector3).y


## Places the disc, in the frame it will be drawn in and after everything that moved the
## actor has run - see [member process_priority] in [method _ready].
##
## Separate from the ray because the two answer questions on different clocks. Ground
## height changes when the actor crosses a ledge, which physics is the right rate for;
## where the actor is standing changes every rendered frame, and sampling that at the
## physics rate makes the shadow visibly trail the sprite whenever the two rates differ.
func _process(_delta: float) -> void:
	if Engine.is_editor_hint():
		return
	if not _grounded:
		visible = false
		return

	var origin := _origin()
	var height := maxf(0.0, origin.y - _ground_y)
	var t := clampf(height / maxf(0.01, max_height), 0.0, 1.0)

	visible = true
	global_position = Vector3(origin.x, _ground_y, origin.z)
	# Held level and unrotated in world space, whatever the parent is doing. The decal
	# projects along its own -Y, so a rotated body would send the projection sideways and
	# the shadow would streak up a wall.
	global_basis = Basis.IDENTITY
	_apply_size(lerpf(1.0, min_scale, t))
	modulate = Color(0, 0, 0, lerpf(opacity, 0.0, t))


## Where to drop the ray from: the target's ground position, at the body's height.
##
## Split on purpose, and the split is the whole point of [member target_path] - see the
## note there. Horizontally the eye should be followed, vertically the body should.
func _origin() -> Vector3:
	var body := get_parent_node_3d()
	var base := body.global_position if body != null else global_position
	if _target == null or _target == body:
		return base
	var follow := _target.global_position
	return Vector3(follow.x, base.y, follow.z)


func _resolve_target() -> void:
	# Resolved once, here, rather than per frame: this runs in the physics step and a
	# NodePath lookup every tick for every actor is work with a known answer.
	_target = get_node_or_null(target_path) as Node3D if not target_path.is_empty() else null
	if not target_path.is_empty() and _target == null:
		push_warning("ActorShadow('%s'): target_path '%s' resolves to nothing, or to a node that is not a Node3D. Falling back to the parent, which will make a grid-stepped actor's shadow snap a cell ahead of it." % [name, target_path])


func _apply_size(scale_factor: float) -> void:
	size = Vector3(radius * 2.0 * scale_factor, thickness, radius * 2.0 * scale_factor)


## A filled circle at texel density, hard-edged. Alpha carries the shape and
## [member modulate] carries the colour, so the fade is a modulate change and never a
## texture rebuild.
func _rebuild_texture() -> void:
	var px := maxi(2, int(round(radius * 2.0 * float(maxi(1, texels_per_unit)))))
	var img := Image.create(px, px, false, Image.FORMAT_RGBA8)
	img.fill(Color(0, 0, 0, 0))
	var centre := float(px) * 0.5
	var r := centre
	for y in px:
		for x in px:
			# Texel centres, so the disc is symmetric rather than a pixel heavier on one
			# side at even diameters.
			var dx := float(x) + 0.5 - centre
			var dy := float(y) + 0.5 - centre
			if dx * dx + dy * dy <= r * r:
				img.set_pixel(x, y, Color(1, 1, 1, 1))
	_generated = ImageTexture.create_from_image(img)
	texture_albedo = _generated


func _set_target_path(value: NodePath) -> void:
	target_path = value
	if is_inside_tree():
		_resolve_target()


func _set_radius(value: float) -> void:
	radius = maxf(0.01, value)
	if is_inside_tree():
		# Only ever replace a texture this class generated - an authored one is a
		# deliberate override and resizing the disc must not silently discard it.
		if texture_albedo == null or texture_albedo == _generated:
			_rebuild_texture()
		_apply_size(1.0)


func _set_texels(value: int) -> void:
	texels_per_unit = maxi(1, value)
	if is_inside_tree() and (texture_albedo == null or texture_albedo == _generated):
		_rebuild_texture()
